const GAS_URL = "YOUR_GAS_URL_HERE";
const STORE_KEY = "goyokiki_v1";
const DEFAULT_CUSTOMERS = [
  { id: "c1", name: "サンプル商事", address: "福島県郡山市〇〇1-2-3", phone: "024-000-0001", note: "" },
  { id: "c2", name: "〇〇自動車", address: "福島県郡山市△△4-5-6", phone: "024-000-0002", note: "" },
];
function getData() { try { const raw = localStorage.getItem(STORE_KEY); if (!raw) return { visits: [], customers: DEFAULT_CUSTOMERS }; return JSON.parse(raw); } catch { return { visits: [], customers: DEFAULT_CUSTOMERS }; } }
function setData(data) { localStorage.setItem(STORE_KEY, JSON.stringify(data)); }
let currentScreen = "calendar", selectedDate = null, editingVisitId = null;
function showScreen(name, title) { document.querySelectorAll(".screen").forEach(s => s.classList.remove("active")); document.getElementById("screen-" + name).classList.add("active"); document.getElementById("page-title").textContent = title; const b = document.getElementById("btn-back"), c = document.getElementById("btn-customers"); if (name === "calendar") { b.classList.add("hidden"); c.style.visibility = "visible"; } else { b.classList.remove("hidden"); c.style.visibility = "hidden"; } window.scrollTo(0, 0); currentScreen = name; }
function goBack() { if (isRecording) stopRecording(); if (currentScreen === "day") { showScreen("calendar", "御用聞きくん"); renderCalendar(); } else if (currentScreen === "form") { showScreen("day", formatDateLabel(selectedDate)); renderDayDetail(selectedDate); } else { showScreen("calendar", "御用聞きくん"); renderCalendar(); } }
let calYear, calMonth;
function initCalendar() { const n = new Date(); calYear = n.getFullYear(); calMonth = n.getMonth(); renderCalendar(); }
function prevMonth() { calMonth--; if (calMonth < 0) { calMonth = 11; calYear--; } renderCalendar(); }
function nextMonth() { calMonth++; if (calMonth > 11) { calMonth = 0; calYear++; } renderCalendar(); }
function renderCalendar() { const data = getData(), year = calYear, month = calMonth; document.getElementById("month-label").textContent = year + "年" + (month + 1) + "月"; const firstDow = new Date(year, month, 1).getDay(), dim = new Date(year, month + 1, 0).getDate(), dip = new Date(year, month, 0).getDate(), today = new Date(); const visitDays = new Set(); const prefix = year + "-" + String(month + 1).padStart(2, "0"); data.visits.forEach(v => { if (v.date && v.date.startsWith(prefix)) visitDays.add(parseInt(v.date.split("-")[2])); }); const DOW = ["日","月","火","水","木","金","土"], DC = ["sun","","","","","","sat"]; let html = DOW.map((d,i) => '<div class="cal-header ' + DC[i] + '">' + d + '</div>').join(""); let dc = 1, nc = 1; for (let i = 0; i < 42; i++) { const col = i % 7; let dn, io = false, date; if (i < firstDow) { dn = dip - firstDow + i + 1; io = true; date = new Date(year, month - 1, dn); } else if (dc <= dim) { dn = dc++; date = new Date(year, month, dn); } else { dn = nc++; io = true; date = new Date(year, month + 1, dn); } const it = !io && date.getFullYear() === today.getFullYear() && date.getMonth() === today.getMonth() && date.getDate() === today.getDate(); const cc = col === 0 ? "sun" : col === 6 ? "sat" : ""; const hv = !io && visitDays.has(dn); const ds = toDateStr(date); const ca = !io ? 'onclick="selectDate(\'' + ds + '\')"' : ""; html += '<div class="cal-day ' + cc + (it ? " today" : "") + (io ? " other-month" : "") + '" ' + ca + '><span class="day-num">' + dn + '</span>' + (hv ? '<div class="day-dot"></div>' : "") + '</div>'; } document.getElementById("cal-grid").innerHTML = html; }
function toDateStr(d) { return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0"); }
function formatDateLabel(ds) { if (!ds) return ""; const d = new Date(ds); return (d.getMonth() + 1) + "月" + d.getDate() + "日"; }
function selectDate(ds) { selectedDate = ds; showScreen("day", formatDateLabel(ds)); renderDayDetail(ds); }
function renderDayDetail(ds) { const data = getData(), visits = data.visits.filter(v => v.date === ds); const d = new Date(ds); document.getElementById("day-title").textContent = d.getFullYear() + "年" + (d.getMonth() + 1) + "月" + d.getDate() + "日の訪問記録"; const con = document.getElementById("visit-list"); if (visits.length === 0) { con.innerHTML = '<div class="empty-state"><div class="empty-icon">📬</div><p>' + (d.getMonth() + 1) + "月" + d.getDate() + "日の訪問記録はありません</p></div>"; return; } visits.sort((a, b) => (a.time || "").localeCompare(b.time || "")); let html = ""; visits.forEach(v => { const tags = []; if (v.memo && v.memo.trim()) tags.push('<span class="tag tag-memo">メモあり</span>'); if (v.partsMemo && v.partsMemo.trim()) tags.push('<span class="tag tag-parts">部品注文</span>'); if (v.recordings && v.recordings.length > 0) tags.push('<span class="tag tag-rec">録音' + v.recordings.length + '件</span>'); if (v.photos && v.photos.length > 0) tags.push('<span class="tag tag-photo">写真' + v.photos.length + '枚</span>'); html += '<div class="visit-card" onclick="editVisit(\'' + v.id + '\')"><div class="vc-name">' + (v.customerName || "（得意先未選択）") + '</div><div class="vc-meta">' + (v.time ? v.time : "") + (v.staff ? " 担当:" + v.staff : "") + '</div><div class="visit-tags">' + tags.join("") + '</div></div>'; }); con.innerHTML = html; }
function escapeHtml(s) { return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); }
let formPhotos = [], formRecordings = [];
function showAddForm() { editingVisitId = null; formPhotos = []; formRecordings = []; renderCustomerOptions(); document.getElementById("f-customer").value = ""; document.getElementById("f-address-display").textContent = ""; document.getElementById("f-gps").value = ""; const n = new Date(); document.getElementById("f-time").value = String(n.getHours()).padStart(2,"0") + ":" + String(n.getMinutes()).padStart(2,"0"); document.getElementById("f-staff").value = ""; document.getElementById("f-memo").value = ""; document.getElementById("f-parts-memo").value = ""; document.getElementById("btn-delete-visit").style.display = "none"; renderPhotoPreviews(); renderRecordingsList(); showScreen("form", "訪問記録 追加"); }
function editVisit(id) { const data = getData(), visit = data.visits.find(v => v.id === id); if (!visit) return; editingVisitId = id; formPhotos = visit.photos ? [...visit.photos] : []; formRecordings = visit.recordings ? visit.recordings.map(r => ({ base64: r.base64, url: r.base64 })) : []; renderCustomerOptions(); document.getElementById("f-customer").value = visit.customerId || ""; onCustomerChange(); document.getElementById("f-gps").value = visit.gps || ""; document.getElementById("f-time").value = visit.time || ""; document.getElementById("f-staff").value = visit.staff || ""; document.getElementById("f-memo").value = visit.memo || ""; document.getElementById("f-parts-memo").value = visit.partsMemo || ""; document.getElementById("btn-delete-visit").style.display = "block"; renderPhotoPreviews(); renderRecordingsList(); showScreen("form", "訪問記録 編集"); }
function renderCustomerOptions() { const data = getData(), sel = document.getElementById("f-customer"); sel.innerHTML = '<option value="">得意先を選択してください</option>'; data.customers.forEach(c => { sel.innerHTML += '<option value="' + c.id + '">' + c.name + '</option>'; }); }
function onCustomerChange() { const data = getData(), id = document.getElementById("f-customer").value, c = data.customers.find(c => c.id === id), el = document.getElementById("f-address-display"); el.textContent = c ? (c.address || "住所未設定") : ""; }
function getGPS() { if (!navigator.geolocation) { showToast("GPS非対応"); return; } showToast("GPS取得中..."); navigator.geolocation.getCurrentPosition(pos => { document.getElementById("f-gps").value = pos.coords.latitude.toFixed(6) + "," + pos.coords.longitude.toFixed(6); showToast("現在地を取得しました"); }, () => showToast("GPS取得に失敗しました")); }
function openCustomerMaps() { const data = getData(), id = document.getElementById("f-customer").value, c = data.customers.find(c => c.id === id); if (!c || !c.address) { showToast("住所を設定してください"); return; } window.open("https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(c.address), "_blank"); }
let mediaRecorder = null, isRecording = false, recordChunks = [];
async function toggleRecording() { if (isRecording) stopRecording(); else await startRecording(); }
async function startRecording() {
  try {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    const mimeType = ["audio/webm;codecs=opus","audio/webm","audio/mp4","audio/ogg"].find(t => MediaRecorder.isTypeSupported(t)) || "";
    mediaRecorder = new MediaRecorder(stream, mimeType ? { mimeType } : {});
    recordChunks = [];
    mediaRecorder.ondataavailable = e => { if (e.data.size > 0) recordChunks.push(e.data); };
    mediaRecorder.onstop = () => {
      stream.getTracks().forEach(t => t.stop());
      const type = mediaRecorder.mimeType || "audio/mp4";
      const blob = new Blob(recordChunks, { type });
      const reader = new FileReader();
      reader.onload = () => { formRecordings.push({ base64: reader.result, url: reader.result }); renderRecordingsList(); };
      reader.readAsDataURL(blob);
    };
    mediaRecorder.start();
    isRecording = true;
    document.getElementById("btn-record").textContent = "停止";
    document.getElementById("btn-record").classList.add("active");
    document.getElementById("recording-indicator").style.display = "flex";
  } catch { showToast("マイクが許可されていません"); }
}
function stopRecording() { if (mediaRecorder && isRecording) { mediaRecorder.stop(); isRecording = false; document.getElementById("btn-record").textContent = "録音開始"; document.getElementById("btn-record").classList.remove("active"); document.getElementById("recording-indicator").style.display = "none"; } }
function renderRecordingsList() { const con = document.getElementById("recordings-list"); if (formRecordings.length === 0) { con.innerHTML = ""; return; } let html = ""; formRecordings.forEach((r, i) => { html += '<div class="recording-item"><audio controls src="' + (r.url || r.base64) + '" style="flex:1;height:36px;"></audio><button class="btn-rec-del" onclick="deleteRecording(' + i + ')">削除</button></div>'; }); con.innerHTML = html; }
function deleteRecording(i) { formRecordings.splice(i, 1); renderRecordingsList(); }
function handlePhotoInput(e) { Array.from(e.target.files).forEach(file => { const img = new Image(); img.onload = () => { const canvas = document.createElement("canvas"); const s = Math.min(1, 1200 / img.width); canvas.width = img.width * s; canvas.height = img.height * s; canvas.getContext("2d").drawImage(img, 0, 0, canvas.width, canvas.height); formPhotos.push(canvas.toDataURL("image/jpeg", 0.72)); renderPhotoPreviews(); }; img.src = URL.createObjectURL(file); }); e.target.value = ""; }
function renderPhotoPreviews() { const con = document.getElementById("photos-preview"); if (formPhotos.length === 0) { con.innerHTML = ""; return; } let html = '<div class="photos-grid">'; formPhotos.forEach((src, i) => { html += '<div class="photo-wrapper"><img src="' + src + '" class="photo-thumb" onclick="viewPhoto(' + i + ')"><button class="photo-del" onclick="deletePhoto(' + i + ')">×</button></div>'; }); con.innerHTML = html + '</div>'; }
function deletePhoto(i) { formPhotos.splice(i, 1); renderPhotoPreviews(); }
function viewPhoto(i) { const w = window.open(); w.document.write('<img src="' + formPhotos[i] + '" style="max-width:100%;height:auto;">'); }
function saveVisit() { if (isRecording) stopRecording(); const data = getData(), cid = document.getElementById("f-customer").value; if (!cid) { showToast("得意先を選択してください"); return; } const c = data.customers.find(c => c.id === cid); const vo = { customerId: cid, customerName: c ? c.name : "", customerAddress: c ? c.address : "", time: document.getElementById("f-time").value, staff: document.getElementById("f-staff").value, memo: document.getElementById("f-memo").value, partsMemo: document.getElementById("f-parts-memo").value, gps: document.getElementById("f-gps").value, photos: [...formPhotos], recordings: formRecordings.map(r => ({ base64: r.base64 })), updatedAt: new Date().toISOString() }; if (editingVisitId) { const idx = data.visits.findIndex(v => v.id === editingVisitId); if (idx >= 0) data.visits[idx] = { ...data.visits[idx], ...vo }; } else { data.visits.push({ id: "v" + Date.now(), date: selectedDate, createdAt: new Date().toISOString(), ...vo }); } setData(data); sendToGas(vo, selectedDate); showToast("保存しました"); setTimeout(goBack, 600); }
function sendToGas(v, date) { if (!GAS_URL || GAS_URL === "YOUR_GAS_URL_HERE") return; fetch(GAS_URL, { method: "POST", body: JSON.stringify({ date, customerName: v.customerName, time: v.time, staff: v.staff, memo: v.memo, partsMemo: v.partsMemo, gps: v.gps, hasPhoto: v.photos.length > 0 ? "写真" + v.photos.length + "枚" : "", hasRecording: v.recordings.length > 0 ? "録音あり" : "" }) }).catch(() => {}); }
function deleteCurrentVisit() { if (!editingVisitId || !confirm("削除しますか？")) return; const data = getData(); data.visits = data.visits.filter(v => v.id !== editingVisitId); setData(data); showToast("削除しました"); editingVisitId = null; showScreen("day", formatDateLabel(selectedDate)); renderDayDetail(selectedDate); }
let editingCustomerId = null;
function showCustomers() { renderCustomerList(); showScreen("customers", "得意先管理"); }
function renderCustomerList() { const data = getData(), con = document.getElementById("customer-list"); if (data.customers.length === 0) { con.innerHTML = '<p style="text-align:center;color:#999;padding:24px;">得意先がありません</p>'; return; } let html = ""; data.customers.forEach(c => { html += '<div class="customer-card"><div class="c-info"><div class="c-name">' + escapeHtml(c.name) + '</div><div class="c-sub">' + (c.address ? escapeHtml(c.address) : "住所未設定") + '</div>' + (c.phone ? '<div class="c-sub">' + escapeHtml(c.phone) + '</div>' : "") + '</div><div class="c-actions"><button class="btn btn-edit" onclick="editCustomer(\'' + c.id + '\')">編集</button><button class="btn btn-del" onclick="deleteCustomer(\'' + c.id + '\')">削除</button></div></div>'; }); con.innerHTML = html; }
function showAddCustomer() { editingCustomerId = null; ["c-name","c-address","c-phone","c-note"].forEach(id => document.getElementById(id).value = ""); document.getElementById("customer-form-title").textContent = "得意先を追加"; document.getElementById("customer-form").style.display = "block"; document.getElementById("customer-form").scrollIntoView({ behavior: "smooth" }); }
function editCustomer(id) { const data = getData(), c = data.customers.find(c => c.id === id); if (!c) return; editingCustomerId = id; document.getElementById("c-name").value = c.name || ""; document.getElementById("c-address").value = c.address || ""; document.getElementById("c-phone").value = c.phone || ""; document.getElementById("c-note").value = c.note || ""; document.getElementById("customer-form-title").textContent = "得意先を編集"; document.getElementById("customer-form").style.display = "block"; document.getElementById("customer-form").scrollIntoView({ behavior: "smooth" }); }
function saveCustomer() { const name = document.getElementById("c-name").value.trim(); if (!name) { showToast("得意先名を入力してください"); return; } const data = getData(), obj = { name, address: document.getElementById("c-address").value.trim(), phone: document.getElementById("c-phone").value.trim(), note: document.getElementById("c-note").value.trim() }; if (editingCustomerId) { const idx = data.customers.findIndex(c => c.id === editingCustomerId); if (idx >= 0) data.customers[idx] = { ...data.customers[idx], ...obj }; } else { data.customers.push({ id: "c" + Date.now(), ...obj }); } setData(data); editingCustomerId = null; document.getElementById("customer-form").style.display = "none"; renderCustomerList(); showToast("保存しました"); }
function cancelCustomerForm() { editingCustomerId = null; document.getElementById("customer-form").style.display = "none"; }
function deleteCustomer(id) { if (!confirm("削除しますか？")) return; const data = getData(); data.customers = data.customers.filter(c => c.id !== id); setData(data); renderCustomerList(); showToast("削除しました"); }
let toastTimer = null;
function showToast(msg) { const t = document.getElementById("toast"); t.textContent = msg; t.style.display = "block"; if (toastTimer) clearTimeout(toastTimer); toastTimer = setTimeout(() => { t.style.display = "none"; }, 2500); }
initCalendar();
